import{a as L,S,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const v="https://pixabay.com/api/",w="50393387-29c967097c23d0e8caeea1a68";async function h(o,s=1,i=15){const r={key:w,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:i};return(await L.get(v,{params:r})).data}const b=document.querySelector(".gallery");document.querySelector("#loader");const q=new S(".gallery a",{captionsData:"alt",captionDelay:250});function f(o){const s=o.map(({webformatURL:i,largeImageURL:r,tags:e,likes:t,views:a,comments:u,downloads:n})=>`
    <li class="gallery-item">
      <a href="${r}">
        <img src="${i}" alt="${e}" loading="lazy" />
      </a>
      <div class="gallery-info">
        <p><b>Likes</b><br />${t}</p>
        <p><b>Views</b><br />${a}</p>
        <p><b>Comments</b><br />${u}</p>
        <p><b>Downloads</b><br />${n}</p>
      </div>
    </li>`).join("");b.insertAdjacentHTML("beforeend",s),q.refresh()}function M(){b.innerHTML=""}function g(){document.querySelector("#loading-message").classList.remove("hidden")}function p(){document.querySelector("#loading-message").classList.add("hidden")}function y(){const o=document.querySelector(".load-more");o&&o.classList.remove("hidden")}function m(){const o=document.querySelector(".load-more");o&&o.classList.add("hidden")}document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector(".form"),s=document.querySelector(".load-more");let i="",r=1,e=0,t=0;const a=15;o.addEventListener("submit",async n=>{n.preventDefault();const l=n.target.elements["search-text"].value.trim();if(!l){c.warning({message:"Please enter a search term!",position:"topRight"});return}i=l,r=1,t=0,M(),m(),g();try{const d=await h(i,r,a);if(e=d.totalHits,d.hits.length===0){c.info({message:"Sorry, no images found. Try another query!",position:"topRight"});return}f(d.hits),t+=d.hits.length,t<e?y():(m(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{c.error({message:"Something went wrong. Try again!",position:"topRight"})}finally{p()}}),s.addEventListener("click",async()=>{r+=1,g(),m();try{const n=await h(i,r,a);if(n.hits.length===0){c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}f(n.hits),t+=n.hits.length,u();const l=Math.ceil(e/a);r<l?y():c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{c.error({message:"Failed to load more images.",position:"topRight"})}finally{p()}});function u(){const n=document.querySelector(".gallery-item");if(!n)return;const{height:l}=n.getBoundingClientRect();window.scrollBy({top:l*2,behavior:"smooth"})}});
//# sourceMappingURL=index.js.map
