import{a as L,S as v,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const w="https://pixabay.com/api/",S="50393387-29c967097c23d0e8caeea1a68";async function f(c,r=1,n=15){const o={key:S,q:c,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n};return(await L.get(w,{params:o})).data}const b=document.querySelector(".gallery");document.querySelector("#loader");const q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(c){const r=c.map(({webformatURL:n,largeImageURL:o,tags:e,likes:t,views:i,comments:h,downloads:u})=>`
    <li class="gallery-item">
      <a href="${o}">
        <img src="${n}" alt="${e}" loading="lazy" />
      </a>
      <div class="gallery-info">
        <p><b>Likes</b><br />${t}</p>
        <p><b>Views</b><br />${i}</p>
        <p><b>Comments</b><br />${h}</p>
        <p><b>Downloads</b><br />${u}</p>
      </div>
    </li>`).join("");b.insertAdjacentHTML("beforeend",r),q.refresh()}function P(){b.innerHTML=""}function p(){document.querySelector("#loading-message").classList.remove("hidden")}function y(){document.querySelector("#loading-message").classList.add("hidden")}document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".form"),r=document.querySelector(".load-more");let n="",o=1,e=0,t=0;const i=15;c.addEventListener("submit",async s=>{s.preventDefault();const l=s.target.elements["search-text"].value.trim();if(!l){a.warning({message:"Please enter a search term!",position:"topRight"});return}n=l,o=1,t=0,P(),m(),p();try{const d=await f(n,o,i);if(e=d.totalHits,d.hits.length===0){a.info({message:"Sorry, no images found. Try another query!",position:"topRight"});return}g(d.hits),t+=d.hits.length,t<e?u():(m(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({message:"Something went wrong. Try again!",position:"topRight"})}finally{y()}}),r.addEventListener("click",async()=>{o+=1,p(),m();try{const s=await f(n,o,i);if(s.hits.length===0){a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}g(s.hits),t+=s.hits.length,h();const l=Math.ceil(e/i);o<l?u():a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{a.error({message:"Failed to load more images.",position:"topRight"})}finally{y()}});function h(){const s=document.querySelector(".gallery-item");if(!s)return;const{height:l}=s.getBoundingClientRect();window.scrollBy({top:l*2,behavior:"smooth"})}function u(){r.classList.remove("hidden")}function m(){r.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
